# Generated by Django 5.1.1 on 2025-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('minimum_free_delivery_order_amount', models.FloatField()),
                ('delivery_charges', models.FloatField()),
            ],
            options={
                'db_table': 'areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('iso3', models.CharField(blank=True, max_length=3)),
                ('numeric_code', models.CharField(blank=True, max_length=3)),
                ('iso2', models.CharField(blank=True, max_length=2)),
                ('phonecode', models.CharField(blank=True, max_length=10)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('currency_name', models.CharField(blank=True, max_length=50)),
                ('currency_symbol', models.CharField(blank=True, max_length=10)),
                ('tld', models.CharField(blank=True, max_length=10)),
                ('native', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100)),
                ('timezones', models.TextField(blank=True)),
                ('translations', models.TextField(blank=True)),
                ('latitude', models.CharField(blank=True, max_length=64)),
                ('longitude', models.CharField(blank=True, max_length=64)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('emojiU', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('flag', models.TextField(blank=True)),
                ('wikiDataId', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryBoys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'delivery_boys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=512)),
                ('variant_name', models.CharField(blank=True, max_length=256)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('tax_percent', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField()),
                ('sub_total', models.FloatField()),
                ('deliver_by', models.CharField(blank=True, max_length=128)),
                ('updated_by', models.IntegerField()),
                ('status', models.CharField(max_length=16)),
                ('active_status', models.CharField(max_length=16)),
                ('hash_link', models.CharField(blank=True, max_length=512)),
                ('is_sent', models.BooleanField()),
                ('is_download', models.BooleanField()),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=12)),
                ('total', models.FloatField()),
                ('delivery_charge', models.FloatField()),
                ('is_delivery_charge_returnable', models.BooleanField()),
                ('wallet_balance', models.FloatField()),
                ('total_payable', models.FloatField()),
                ('promo_code', models.CharField(blank=True, max_length=28)),
                ('promo_discount', models.FloatField()),
                ('discount', models.FloatField()),
                ('final_total', models.FloatField()),
                ('payment_method', models.CharField(max_length=16)),
                ('latitude', models.CharField(blank=True, max_length=256)),
                ('longitude', models.CharField(blank=True, max_length=256)),
                ('address_text', models.TextField(blank=True, db_column='address')),
                ('delivery_time', models.CharField(blank=True, max_length=128)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=1024)),
                ('active_status', models.CharField(max_length=16)),
                ('date_added', models.DateTimeField()),
                ('otp', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=254)),
                ('notes', models.CharField(blank=True, max_length=512)),
                ('attachments', models.CharField(blank=True, max_length=2048)),
                ('is_local_pickup', models.BooleanField()),
                ('is_pos_order', models.BooleanField()),
                ('seller_notes', models.TextField(blank=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('already_print_once', models.BooleanField()),
                ('is_printed', models.IntegerField()),
                ('offer_type_details', models.TextField()),
                ('offer_discount', models.FloatField()),
                ('city', models.IntegerField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_value_ids', models.TextField(blank=True)),
                ('attribute_set', models.CharField(blank=True, max_length=255)),
                ('price', models.FloatField()),
                ('special_price', models.FloatField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('breadth', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('images', models.TextField(blank=True)),
                ('availability', models.BooleanField()),
                ('status', models.BooleanField()),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'product_variants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=16)),
                ('remarks', models.TextField(blank=True)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'return_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=16)),
                ('txn_id', models.CharField(max_length=255)),
                ('payu_txn_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=16)),
                ('currency_code', models.CharField(blank=True, max_length=10)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField()),
                ('date_created', models.DateTimeField()),
                ('is_refund', models.BooleanField()),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zipcodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'zipcodes',
                'managed': False,
            },
        ),
    ]
