# Generated by Django 5.1.1 on 2025-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255, null=True)),
                ('banner', models.CharField(max_length=255, null=True)),
                ('row_order', models.IntegerField()),
                ('status', models.BooleanField()),
                ('clicks', models.IntegerField()),
                ('city', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('promo_code', models.CharField(max_length=50)),
                ('message', models.TextField(null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_users', models.IntegerField()),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_type', models.CharField(max_length=50)),
                ('max_discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repeat_usage', models.BooleanField()),
                ('no_of_repeat_usage', models.IntegerField(null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField()),
                ('is_cashback', models.BooleanField()),
                ('list_promocode', models.BooleanField()),
                ('is_specific_users', models.BooleanField()),
                ('users_id', models.TextField(null=True)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'promocode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WalletTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'wallet_transactions',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DeliveryBoys',
        ),
    ]
