# Generated by Django 5.1.1 on 2025-06-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_categories_promocode_wallettransactions_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promocode',
            table='promo_codes',
        ),
    ]
