# Generated by Django 5.1.1 on 2025-07-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_promocode_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': True},
        ),
    ]
